### ISSUE TITLE
Promisify `child_process.exec`

### ISSUE THREAD

**Issue by Aprillion** [OpenSourceRaidGuild/unimported#15]
`exec` function from child_process in our test is using a callback - which is OK if the test needs to execute only 1 command, but will get ugly if we need a sequence of 2 or more commands in 1 test => we should promisify it.

a) find a native Node version that is a Promise already, or some small library

b) something like following (plz test that it works and that the error message is nice if you fail some test on purpose):

```js
import {exec as origExec} from 'child_process'

export function exec(command) {
  return new Promise((resolve, reject) => {
     origExec(command, (error, stdout, stderr) => {
       if (error || stderr) return reject({error, stdout, stderr})
       resolve(stdout)
     })
  })
}
```

(feel free to assign this ticket to yourself and work on it)

**Comment by mpeyper** [comment]
It might not be applicable to the signature of `exec` , but NodeJS does have [`promisify` utility](https://nodejs.org/dist/latest-v14.x/docs/api/util.html#util_util_promisify_original) already that could be investigated.

**Comment by YPAzevedo** [comment]
The only thing about the node promisify is that it expects the callback to have a `(err, value) => {}` signature, it seems like we have `(error, stdout, stderr) => {}`. Not sure it would work 🤔 

https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original

**Comment by mpeyper** [comment]
Yeah. There's a whole section in their docs about custom promisify symbols and whatnot, but I've only used the normal version before. Might not be helpful, just thought it was worth mentioning 🤷‍♂️

**Comment by juhanakristian** [comment]
@mpeyper Pushed a promisified exec with his [PR](https://github.com/OpenSourceRaidGuild/unimported/pull/22)

```ts
function exec(
  command: string,
  options: { cwd: string },
): Promise<{ exitCode: number | null; stdout: string }> {
  return new Promise((resolve) => {
    const process = childProcess.exec(command, options, (_error, stdout) => {
      resolve({ exitCode: process.exitCode, stdout });
    });
  });
}
```

While trying to run tests I'm getting an error `Property 'exitCode' does not exist on type 'ChildProcess'`

We could also use `execSync` which throws an error if the exit code is non-zero.
```ts
function exec(
  command: string,
  options: { cwd: string },
): Promise<{ exitCode: number | null; stdout: string }> {
  return new Promise((resolve) => {
    try {
      const buffer = childProcess.execSync(command, options);
      resolve({ exitCode: 0, stdout: buffer.toString() });
    } catch (ex) {
      resolve({ exitCode: ex.status, stdout: ex.stdout.toString() });
    }
  });
}
```

**Comment by juhanakristian** [comment]
The tests did pass on CI so I'm not sure what's going on 🤔

**Comment by mpeyper** [comment]
I also found [this](https://github.com/OpenSourceRaidGuild/unimported/pull/22#discussion_r561910289) after it was merged. I'm going to investigate it today if I get time.
