### ISSUE TITLE
Test monorepo

### ISSUE THREAD

**Issue by Aprillion** [OpenSourceRaidGuild/unimported#36]
(free for assignment to any raid member)

From coverage report of `meta.ts`, we need to test a project with "monorepo" structure (not sure what it means exactly, if not obvious by analyzing code, we will need to ask Stephan):

<img width="615" alt="Screenshot 2021-01-28 at 13 40 23" src="https://user-images.githubusercontent.com/1087670/106139958-6bee2c80-616e-11eb-9134-f3aa73e41e60.png">

**Comment by datner** [comment]
this seems tricky to test... Lets give it a try

**Comment by datner** [comment]
the monorepo structure probably just means ts paths or lerna-like projects, I'll tackle the ts one first I think
