### ISSUE TITLE
Test meteor

### ISSUE THREAD

**Issue by Aprillion** [OpenSourceRaidGuild/unimported#37]
(free for assignment to any raid member)

From coverage report of `meta.ts`, we need to test a project with "meteor" structure (not sure what it means exactly, if not obvious by analyzing code, we will need to ask Stephan):

![Screenshot 2021-01-28 at 13 44 15](https://user-images.githubusercontent.com/1087670/106140362-f767bd80-616e-11eb-987b-88c0a37afc60.png)

Note: we should test the `return` branch, not a priority to cover `throw new Error` on screenshot.

**Comment by smeijer** [comment]
Meteor projects have 2 ways of resolving modules. 

1) just load all. Let's ignore this one for `unimported`. It doesn't make sense to test "unimported files" when all files are eagerly loaded.

2) using `package.json` to specify the client and server entry points. This is the one supported by `unimported`.

    ```json
    {
      "meteor": {
        "mainModule": {
          "client": "./src/client/main.js",
          "server": "./src/server/main.js"
      }
    }
    ```

So all it means for `unimported` is that the entry files are not taken from `package.json#main`, but from `package.json#meteor.mainModule.client` and `package.json#meteor.mainModule.server`. Unimported also detects meteor projects by checking for the `.meteor` dir, that every meteor project has in the project root (next to `package.json`).

**Comment by juhanakristian** [comment]
Thank's for the explanation @smeijer I will take a look at this.
